### ISSUE TITLE
Write unassigned barcodes to file

### ISSUE THREAD

**Issue by kylebittinger** [PennChopMicrobiomeProgram/dnabc#15]
We should write the top 100 to a table

**Comment by kylebittinger** [comment]
This change could be implemented in BarcodeAssigner.assign():

https://github.com/PennChopMicrobiomeProgram/dnabc/blob/master/dnabclib/assigner.py#L65

Best strategy is probably to initiate a collections.Counter object for unassigned barcodes in BarcodeAssigner.__init__(), then write to it in BarcodeAssigner.assign(), then save the top hits to a file at the end of the main function for the script.

**Comment by Ulthran** [comment]
#16
